sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - git clone git://github.com/ome/omero-test-infra .omero

script:
  - python setup.py sdist
  # .omero/docker app
